function boollean=Contains(snode1,snode2)
%snode1°üº¬snode2
if snode1.NO~=snode2.NO && ...
        strcmp(snode1.class,'root') && ...
        snode1.minX<=snode2.x_centroid && ...
        snode2.x_centroid<snode1.maxX && ...
        snode1.minY<=snode2.y_centroid && ...
        snode2.y_centroid<snode1.maxY
    boollean=1;
else
    boollean=0;
end
    